sqlcmd -S . -E -Q "ALTER DATABASE [kr1] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; RESTORE DATABASE [kr1] FROM  DISK = N'G:\kr1.bak' WITH  FILE = 1,  NOUNLOAD,  REPLACE,  STATS = 10;ALTER DATABASE [kr1] SET MULTI_USER"
pause
