CREATE       PROC [dbo].[usp_GMP_Select]
    @N_EL_NUM varchar(50)
AS

SET NOCOUNT ON 

SELECT 
	N_EL_NUM, N_TYPE_STR, N_STATUS_STR, N_SUMMA, ADDRESS, N_PLAT_NAME, N_SUMMA_DOLG, N_UIN, FILE_NAME, N_CUID, N_DATE_PROVODKA, N_DATE_PERIOD, N_RDATE, N_DATE_VVOD, date_edit, user_edit 
FROM   dbo.GMP
WHERE  N_EL_NUM = @N_EL_NUM
go

